---
- hosts: all
  become: yes
  tasks:
  - name: i want install git on ubuntu only
    apt:
      name: git
      state: present
    when: ansible_os_family =="ubuntu"


  - name: i want install webserver on ubuntu only
    apt:
      name: apache2
      state: started
    when: ansible_os_family =="ubuntu" 