---
- hosts: all
  become: yes
  tasks:
  - name: i want install webserver on  only ubuntu nodes
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="Debian"


  - name: i want start webserver on  only ubuntu nodes
    service:
      name: apache2
      state: started
    when: ansible_os_family =="Debian" 

  - name: i want install web server on only RedHat nodes
    apt:
     name: httpd
     state: present
    when: ansible_os_family == "RedHat"


  - name: i want start webserver on only RedHat nodes
    service: httpd
    state: started
  when: ansible_os_family == "RedHat"
  
 