--- 
- hosts: all
  become: yes
  tasks:
  - name: install webserver only on ubuntu nodes
    apt:
      name: git
      state: present
    when:  ansible_os_family":"Debian"




  - name: install webserver only on ubuntu nodes
    apt:
      name: git
      state: present
    when:  ansible_os_family":"Debian"