--- 
- hosts: all
  become: yes
  tasks:
  - name: i want install webserver only on ubuntu nodes
    apt:
      name: apache2
      state: present
    when:  ansible_os_family":"Debian"




  - name: i want install webserver only on ubuntu nodes
    apt:
      name: apache2
      state: stared
    when:  ansible_os_family":"Debian"